"""
synthetic_flow_generator.py
--------------------------
Synthetic network-flow source for the IDS dashboard.

Generates model-compatible synthetic flow records and feeds them to the
existing inference engine.

The generator does NOT assign the final attack label itself. Instead, it
searches for feature combinations that the currently loaded ML model
actually predicts as the requested class.

This is especially important for U2R/Critical demonstrations because U2R
may occupy a relatively small region of the trained model's feature space.

The final label shown by the dashboard always comes from the real ML model.
"""

from __future__ import annotations

import random
import threading
import time
from typing import Dict, Optional

from config import SYNTHETIC_FLOW_INTERVAL_SECONDS, SYNTHETIC_SOURCE_NETWORKS
from preprocessing import FlowPreprocessor


class SyntheticFlowGenerator:
    """Continuously generate model-compatible synthetic network flows."""

    # All classes available in the trained Random Forest.
    SCENARIOS = ("Normal", "DoS", "Probe", "R2L", "U2R")

    # Desired demonstration frequency.
    # These are NOT ground-truth labels. They only determine which class
    # the generator attempts to find in the model's prediction space.
    SCENARIO_WEIGHTS = {
        "Normal": 70,
        "DoS": 12,
        "Probe": 8,
        "R2L": 6,
        "U2R": 4,
    }
    

    # Number of model evaluations allowed when searching for a target.
    # U2R gets a larger search budget because it is usually the hardest
    # class to reach in the synthetic feature space.
    SEARCH_BUDGET = {
        "Normal": 80,
        "DoS": 180,
        "Probe": 250,
        "R2L": 500,
        "U2R": 3000,
    }

    # Confidence requirement for accepting a searched target.
    MIN_TARGET_CONFIDENCE = 0.55

    def __init__(
        self,
        output_queue,
        interval: float = SYNTHETIC_FLOW_INTERVAL_SECONDS,
    ):
        self.output_queue = output_queue
        self.interval = max(float(interval), 0.1)

        self._stop_event = threading.Event()
        self._pause_event = threading.Event()
        self._thread: Optional[threading.Thread] = None

        self._preprocessor = FlowPreprocessor()

        # Successful feature patterns are cached.
        #
        # Once the generator discovers a feature vector that the model
        # confidently predicts as U2R, future U2R flows are generated by
        # perturbing that successful vector rather than searching from zero
        # every time.
        self._prototype_cache: Dict[str, Dict] = {}

        self._cache_lock = threading.Lock()

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def start(self) -> None:
        if self._thread and self._thread.is_alive():
            return

        self._stop_event.clear()
        self._pause_event.clear()

        self._thread = threading.Thread(
            target=self._run,
            daemon=True,
            name="synthetic-flow-generator",
        )
        self._thread.start()

    def stop(self) -> None:
        self._stop_event.set()
        self._pause_event.clear()

        if self._thread:
            self._thread.join(timeout=3)

        self._thread = None

    def pause(self) -> None:
        if self._thread and self._thread.is_alive():
            self._pause_event.set()

    def resume(self) -> None:
        if self._thread and self._thread.is_alive():
            self._pause_event.clear()

    @property
    def status(self) -> str:
        if not self._thread or not self._thread.is_alive():
            return "stopped"

        return "paused" if self._pause_event.is_set() else "running"

    # ------------------------------------------------------------------
    # Main generation loop
    # ------------------------------------------------------------------

    def _run(self) -> None:
        while not self._stop_event.is_set():

            if self._pause_event.is_set():
                self._stop_event.wait(0.2)
                continue

            try:
                flow = self.generate_flow()

                # Never block indefinitely if the inference queue is full.
                self.output_queue.put(flow)

            except Exception:
                # The generator must never kill its background thread because
                # of one malformed candidate.
                import logging

                logging.getLogger("nids.synthetic").exception(
                    "Failed to generate synthetic flow"
                )

            self._stop_event.wait(self.interval)

    # ------------------------------------------------------------------
    # Scenario selection
    # ------------------------------------------------------------------

    def _choose_target(self) -> str:
        scenarios = list(self.SCENARIO_WEIGHTS.keys())
        weights = list(self.SCENARIO_WEIGHTS.values())

        return random.choices(
            scenarios,
            weights=weights,
            k=1,
        )[0]

    # ------------------------------------------------------------------
    # Public flow generation
    # ------------------------------------------------------------------

    def generate_flow(self) -> Dict:
        """
        Generate a flow whose final class is determined by the real ML model.

        The requested scenario is only a search target.

        If a suitable target cannot be found, the generator falls back to a
        normal flow rather than falsely assigning an attack label.
        """

        target = self._choose_target()

        # --------------------------------------------------------------
        # First try an already discovered prototype.
        # --------------------------------------------------------------
        prototype = self._get_prototype(target)

        if prototype is not None:

            for _ in range(30):
                candidate = self._mutate_prototype(prototype, target)

                try:
                    predicted, confidence, _ = self._preprocessor.predict(
                        candidate
                    )
                except Exception:
                    continue

                if (
                    predicted == target
                    and confidence >= self.MIN_TARGET_CONFIDENCE
                ):
                    candidate["_synthetic_scenario"] = target
                    return candidate

        # --------------------------------------------------------------
        # Search the model's feature space.
        # --------------------------------------------------------------
        budget = self.SEARCH_BUDGET.get(target, 250)

        for _ in range(budget):

            candidate = self._candidate(target)

            try:
                predicted, confidence, _ = self._preprocessor.predict(
                    candidate
                )
            except Exception:
                continue

            if (
                predicted == target
                and confidence >= self.MIN_TARGET_CONFIDENCE
            ):
                candidate["_synthetic_scenario"] = target

                # Store a clean prototype without metadata.
                self._store_prototype(target, candidate)

                return candidate

        # --------------------------------------------------------------
        # Safe fallback.
        #
        # We never pretend that a failed search produced the requested
        # attack type.
        # --------------------------------------------------------------
        candidate = self._candidate("Normal")

        try:
            predicted, confidence, _ = self._preprocessor.predict(candidate)
        except Exception:
            predicted = "Normal"
            confidence = 0.0

        candidate["_synthetic_scenario"] = "Normal"
        candidate["_synthetic_generation_target"] = target
        candidate["_synthetic_search_failed"] = True

        return candidate

    # ------------------------------------------------------------------
    # Prototype cache
    # ------------------------------------------------------------------

    def _get_prototype(self, target: str) -> Optional[Dict]:
        with self._cache_lock:
            prototype = self._prototype_cache.get(target)

            if prototype is None:
                return None

            return dict(prototype)

    def _store_prototype(self, target: str, candidate: Dict) -> None:
        prototype = {
            "Protocol": candidate.get("Protocol"),
            "Duration": candidate.get("Duration"),
            "BytesSent": candidate.get("BytesSent"),
            "BytesReceived": candidate.get("BytesReceived"),
            "FailedLogins": candidate.get("FailedLogins"),
            "Connections": candidate.get("Connections"),
        }

        with self._cache_lock:
            self._prototype_cache[target] = prototype

    # ------------------------------------------------------------------
    # Prototype mutation
    # ------------------------------------------------------------------

    def _mutate_prototype(
        self,
        prototype: Dict,
        scenario: str,
    ) -> Dict:
        """
        Create a nearby candidate around a previously successful feature
        vector.

        This makes rare classes such as U2R much easier to reproduce after
        the first successful discovery.
        """

        duration = float(prototype.get("Duration", 1.0))
        sent = float(prototype.get("BytesSent", 100.0))
        received = float(prototype.get("BytesReceived", 100.0))
        failed = int(prototype.get("FailedLogins", 0))
        connections = float(prototype.get("Connections", 1.0))

        # Small multiplicative perturbations preserve the general region
        # discovered by the model.
        duration *= random.uniform(0.75, 1.25)
        sent *= random.uniform(0.75, 1.25)
        received *= random.uniform(0.75, 1.25)
        connections *= random.uniform(0.75, 1.25)

        failed += random.choice([-1, 0, 0, 0, 1])

        duration = max(duration, 0.001)
        sent = max(sent, 0.0)
        received = max(received, 0.0)
        failed = max(failed, 0)
        connections = max(connections, 0.1)

        return self._build_flow(
            protocol=random.choice(("TCP", "UDP", "ICMP")),
            duration=duration,
            sent=sent,
            received=received,
            failed=failed,
            connections=connections,
        )

    # ------------------------------------------------------------------
    # Candidate generation
    # ------------------------------------------------------------------

    def _candidate(self, scenario: str) -> Dict:
        """
        Generate a broad candidate feature vector.

        The ranges deliberately overlap more widely than the original
        generator so that rare classes have a better chance of being reached
        by the trained Random Forest.
        """

        protocol = random.choice(("TCP", "UDP", "ICMP"))

        if scenario == "Normal":

            duration = random.uniform(0.2, 8)
            sent = random.uniform(20, 900)
            received = random.uniform(20, 1200)
            failed = random.randint(0, 1)
            connections = random.uniform(1, 12)

        elif scenario == "DoS":

            duration = random.uniform(0.001, 5)
            sent = random.uniform(500, 20000)
            received = random.uniform(0, 5000)
            failed = random.randint(0, 8)
            connections = random.uniform(15, 150)

        elif scenario == "Probe":

            duration = random.uniform(0.001, 5)
            sent = random.uniform(5, 3000)
            received = random.uniform(0, 2000)
            failed = random.randint(0, 5)
            connections = random.uniform(10, 150)

        elif scenario == "R2L":

            duration = random.uniform(0.05, 40)
            sent = random.uniform(100, 12000)
            received = random.uniform(0, 5000)
            failed = random.randint(2, 15)
            connections = random.uniform(1, 50)

        else:
            # ----------------------------------------------------------
            # U2R
            #
            # U2R is usually difficult to reach with a single narrow
            # feature range. Generate several broad patterns.
            # ----------------------------------------------------------

            profile = random.randint(0, 5)

            if profile == 0:
                duration = random.uniform(0.001, 2)
                sent = random.uniform(50, 2500)
                received = random.uniform(0, 1500)
                failed = random.randint(0, 5)
                connections = random.uniform(1, 15)

            elif profile == 1:
                duration = random.uniform(0.1, 15)
                sent = random.uniform(500, 6000)
                received = random.uniform(10, 2500)
                failed = random.randint(2, 12)
                connections = random.uniform(1, 20)

            elif profile == 2:
                duration = random.uniform(1, 60)
                sent = random.uniform(100, 10000)
                received = random.uniform(0, 5000)
                failed = random.randint(0, 10)
                connections = random.uniform(1, 40)

            elif profile == 3:
                duration = random.uniform(0.001, 10)
                sent = random.uniform(1000, 15000)
                received = random.uniform(0, 1000)
                failed = random.randint(0, 15)
                connections = random.uniform(1, 10)

            elif profile == 4:
                duration = random.uniform(5, 100)
                sent = random.uniform(100, 8000)
                received = random.uniform(100, 8000)
                failed = random.randint(0, 15)
                connections = random.uniform(1, 30)

            else:
                duration = random.uniform(0.001, 100)
                sent = random.uniform(0, 20000)
                received = random.uniform(0, 10000)
                failed = random.randint(0, 20)
                connections = random.uniform(0.1, 100)

        return self._build_flow(
            protocol=protocol,
            duration=duration,
            sent=sent,
            received=received,
            failed=failed,
            connections=connections,
        )

    # ------------------------------------------------------------------
    # Flow construction
    # ------------------------------------------------------------------

    def _build_flow(
        self,
        protocol: str,
        duration: float,
        sent: float,
        received: float,
        failed: int,
        connections: float,
    ) -> Dict:

        src_prefix, dst_prefix = random.choice(
            SYNTHETIC_SOURCE_NETWORKS
        )

        src_ip = f"{src_prefix}.{random.randint(2, 254)}"
        dst_ip = f"{dst_prefix}.{random.randint(2, 254)}"

        return {
            "Protocol": protocol,
            "Duration": round(max(duration, 0.001), 4),
            "BytesSent": round(max(sent, 0.0), 2),
            "BytesReceived": round(max(received, 0.0), 2),
            "FailedLogins": max(int(failed), 0),
            "Connections": round(max(connections, 0.1), 2),

            "_source_ip": src_ip,
            "_destination_ip": dst_ip,
            "_src_port": random.randint(1024, 65535),
            "_dst_port": random.choice(
                [
                    21,
                    22,
                    23,
                    25,
                    53,
                    80,
                    443,
                    3389,
                    8080,
                ]
            ),

            "_packet_count": random.randint(2, 80),
            "_synthetic": True,
        }


# ----------------------------------------------------------------------
# Standalone test
# ----------------------------------------------------------------------

def _demo():
    """
    Standalone generator test.

    This does not start the FastAPI dashboard. It simply checks whether the
    generator can discover different model prediction classes.
    """

    import logging
    from collections import Counter
    import queue

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )

    q = queue.Queue()

    generator = SyntheticFlowGenerator(
        q,
        interval=0.1,
    )

    print()
    print("=" * 70)
    print("Synthetic flow generator test")
    print("=" * 70)
    print()

    results = Counter()

    for index in range(100):

        flow = generator.generate_flow()

        try:
            predicted, confidence, _ = generator._preprocessor.predict(flow)
        except Exception:
            predicted = "ERROR"
            confidence = 0.0

        results[predicted] += 1

        print(
            f"{index + 1:03d} | "
            f"predicted={predicted:<6} | "
            f"confidence={confidence:.3f} | "
            f"target={flow.get('_synthetic_scenario')}"
        )

    print()
    print("=" * 70)
    print("Prediction distribution")
    print("=" * 70)

    for label, count in sorted(results.items()):
        print(f"{label:<10}: {count}")

    print()


if __name__ == "__main__":
    _demo()
    